### ISSUE TITLE
Receive Server 500 Error on changing password

### ISSUE THREAD

**Issue by hybrid1969** [evewspace/eve-wspace#211]
Users that have registered with email addresses get error 500 when using the password rest function.

And when i try to reset from the Admin panel i also get server 500 error.

I have checked the permissions and cant see anything obvious as everything else appears to work correctly.

Any ideas what may be the cause and can we have a FAQ or similar of know config/setup issues and errors maybe.

**Comment by Maarten28** [comment]
Through the admin menu might have been caused by not having setup a proper way to send emails. In the new PR in the admin menu this has been changed into a checkbox so this doesn't happen again. 

With regards to the normal change by a user I am unsure how that could be caused. I have not been able to reproduce it on my dev environment.
